import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from '@mui/material/Button';
import Navbar from './Navbar/Navbar';
import Hero from './Hero/Hero';
import Script from 'next/script'


interface Props {
    children: React.ReactNode,
  };

export const Layout = ({ children }: Props) => {
  return (
    <div>
      <Head>
        <title>Flag Prototype</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
        <script async src="https://global.localizecdn.com/localize.js"></script>
        <script>
          {`!function(a){if(!a.Localize){a.Localize={};for(var e=["translate","untranslate","phrase","initialize","translatePage","setLanguage","getLanguage","getSourceLanguage","detectLanguage","getAvailableLanguages","untranslatePage","bootstrap","prefetch","on","off","hideWidget","showWidget"],t=0;t<e.length;t++)a.Localize[e[t]]=function(){}}}(window);`}
        </script>
        <script>
          {`Localize.initialize({ key: 'mH7ikNOPaO1R1', rememberLanguage: true, });`}
    </script>
      </Head>
      <Navbar />
      <main className={styles.main}>
       {children}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
